import React from 'react';
import { FiShield, FiLock, FiCheckCircle, FiCpu } from 'react-icons/fi';
import { motion } from 'framer-motion';

const FairnessAuditCard = () => {
  const auditPoints = [
    {
      icon: FiLock,
      color: 'text-info',
      title: 'Tamper-Proof Ledger',
      desc: 'Transaction hash logged and immutable.',
    },
    {
      icon: FiCpu,
      color: 'text-warning',
      title: 'Cryptographic RNG',
      desc: 'NIST-compliant random entropy seeds.',
    },
    {
      icon: FiCheckCircle,
      color: 'text-success',
      title: 'Audit Certified',
      desc: 'Real-time fraud and bot checks passed.',
    },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.5 }}
      className="p-3 p-sm-4 rounded-4 mb-4 mb-md-5 text-white"
      style={{
        background: 'rgba(15, 20, 39, 0.75)',
        border: '1px solid rgba(255, 255, 255, 0.08)',
      }}
    >
      <div className="d-flex align-items-center gap-2 mb-2 mb-sm-3">
        <FiShield className="text-success" size={22} />
        <h5 className="fw-bold mb-0" style={{ fontSize: 'clamp(0.95rem, 2.5vw, 1.15rem)' }}>
          Fairness & RNG Audit Verification
        </h5>
      </div>

      <p className="small mb-3" style={{ color: '#cbd5e1', fontSize: '0.84rem' }}>
        Every winner draw is generated by a server-side CSPRNG algorithm. Entries are locked the second countdown reaches zero to maintain 100% integrity.
      </p>

      <div className="row g-2 g-sm-3">
        {auditPoints.map((item, idx) => {
          const Icon = item.icon;
          return (
            <div key={item.title} className="col-12 col-sm-6 col-md-4">
              <motion.div
                whileHover={{ y: -3 }}
                className="p-3 rounded-3 h-100"
                style={{
                  background: 'rgba(10, 14, 28, 0.6)',
                  border: '1px solid rgba(255, 255, 255, 0.05)',
                }}
              >
                <div className="d-flex align-items-center gap-2 mb-1">
                  <Icon className={item.color} size={16} />
                  <strong className="text-white small">{item.title}</strong>
                </div>
                <span className="small d-block" style={{ color: '#94a3b8', fontSize: '0.76rem' }}>
                  {item.desc}
                </span>
              </motion.div>
            </div>
          );
        })}
      </div>
    </motion.div>
  );
};

export default FairnessAuditCard;
