import React from 'react';
import { FiShield, FiLock, FiCheckCircle, FiCpu } from 'react-icons/fi';

const FairnessAuditCard = () => {
  return (
    <div
      className="p-4 rounded-4 mb-5 text-white"
      style={{
        background: 'rgba(15, 20, 39, 0.75)',
        border: '1px solid rgba(255, 255, 255, 0.08)',
      }}
    >
      <div className="d-flex align-items-center gap-2 mb-3">
        <FiShield className="text-success" size={22} />
        <h5 className="fw-bold mb-0">Fairness & RNG Audit Verification</h5>
      </div>

      <p className="text-muted small mb-3" style={{ color: '#cbd5e1 !important' }}>
        Every winner draw is generated by a server-side CSPRNG algorithm. Entries are locked the second countdown reaches zero to maintain 100% integrity.
      </p>

      <div className="row g-3">
        <div className="col-12 col-md-4">
          <div className="p-3 rounded-3" style={{ background: 'rgba(10, 14, 28, 0.6)', border: '1px solid rgba(255, 255, 255, 0.05)' }}>
            <div className="d-flex align-items-center gap-2 mb-1">
              <FiLock className="text-info" size={16} />
              <strong className="text-white small">Tamper-Proof Ledger</strong>
            </div>
            <span className="text-muted small" style={{ color: '#94a3b8' }}>Transaction hash logged and immutable.</span>
          </div>
        </div>

        <div className="col-12 col-md-4">
          <div className="p-3 rounded-3" style={{ background: 'rgba(10, 14, 28, 0.6)', border: '1px solid rgba(255, 255, 255, 0.05)' }}>
            <div className="d-flex align-items-center gap-2 mb-1">
              <FiCpu className="text-warning" size={16} />
              <strong className="text-white small">Cryptographic RNG</strong>
            </div>
            <span className="text-muted small" style={{ color: '#94a3b8' }}>NIST-compliant random entropy seeds.</span>
          </div>
        </div>

        <div className="col-12 col-md-4">
          <div className="p-3 rounded-3" style={{ background: 'rgba(10, 14, 28, 0.6)', border: '1px solid rgba(255, 255, 255, 0.05)' }}>
            <div className="d-flex align-items-center gap-2 mb-1">
              <FiCheckCircle className="text-success" size={16} />
              <strong className="text-white small">Audit Certified</strong>
            </div>
            <span className="text-muted small" style={{ color: '#94a3b8' }}>Real-time fraud and bot checks passed.</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FairnessAuditCard;
